"""The known-gaps document, generated from the scenarios themselves.

``docs/known-gaps.md`` is this function's output, and a test asserts the file
still matches. Hand-maintaining the table was the failure mode: ``xpass``
catches a gap that *closes*, but nothing catches a row whose wording drifted,
a row deleted from the code, or a new gap nobody wrote down.
"""

from llm_browser_conformance.drivers import CONFORMANCE_DRIVERS
from llm_browser_conformance.scenarios import ALL_SCENARIOS

HEADER = """<!-- Generated by `llm-browser-check --gaps`; edit the scenarios, not this file. -->

# Known gaps

Behaviour the conformance suite says should hold and does not. Each row is a
`known_gaps` entry in `src/llm_browser_conformance/checks/`, reported as
`xfail` by `llm-browser-check` and as an expected failure under pytest. A row
that starts passing turns into `XPASS`, which fails the run: a gap table that
has gone stale is a lie about what the drivers do.

An unimplemented API is not a gap — it reports `skip` with the driver's own
`NotImplementedError` message, and is not listed here.

| scenario | driver | gap |
| --- | --- | --- |
"""


def cell(text: str) -> str:
    """``<select>`` would render as an invisible HTML tag inside a table."""
    return text.replace("|", r"\|").replace("<", "&lt;")


def gap_rows() -> list[tuple[str, str, str]]:
    order = {name: i for i, name in enumerate(CONFORMANCE_DRIVERS)}
    return [
        (scenario.name, driver, reason)
        for scenario in ALL_SCENARIOS
        for driver, reason in sorted(
            scenario.known_gaps.items(), key=lambda item: order.get(item[0], 99)
        )
    ]


def known_gaps_document() -> str:
    rows = "".join(
        f"| {cell(name)} | {driver} | {cell(reason)} |\n"
        for name, driver, reason in gap_rows()
    )
    return HEADER + rows
