"""The reference half of the docs, rendered from the source by griffe2md.

This module names *what* to document; griffe reads the signatures, docstrings
and ``Field(description=)`` out of the source statically, and griffe2md turns
them into markdown. The build hook (``hatch_build.py``) runs it, so
``docs/reference/*.md`` is a build artifact rather than a committed file.

Nothing here imports ``llm_browser``: the hook loads this file on its own, in
a build environment where the package is source, not an installed dependency.
"""

from collections.abc import Callable
from pathlib import Path
from typing import Any, NamedTuple

import griffe
import griffe2md

PACKAGE = "llm_browser"

HEADER = (
    "<!-- Generated by `llm-browser docs --write` from the source; "
    "edit the code, not this file. -->\n"
)

# griffe2md's defaults are written for a docs site with an index and full
# dotted paths. A model reads one document at a time, so: plain names as
# headings, no summary index, source order, signatures with their annotations,
# and inherited members left to the base class that declares them.
CONFIG: dict[str, Any] = {
    **griffe2md.default_config,
    "heading_level": 2,
    "show_root_heading": True,
    "show_root_full_path": False,
    "show_object_full_path": False,
    "show_root_members_full_path": False,
    "show_bases": True,
    "summary": False,
    "inherited_members": False,
    "members_order": "source",
    "show_signature_annotations": True,
    "separate_signature": True,
    # `model_config` is pydantic's own plumbing, not a field a flow writes.
    "filters": ["!^_", "!^model_config$"],
}

# One member of a step model carries no docstring and is the thing a flow
# author most needs: `action: Literal["click"]`. So undocumented members stay
# visible everywhere except the session, where they are `self.x = x` noise.
QUIET = {"show_if_no_docstring": False}

Members = Callable[[griffe.Module], list[str]]


class Document(NamedTuple):
    """A generated file: its heading, its opening line, and what it renders."""

    title: str
    intro: str
    members: Members
    config: dict[str, Any] = {}


def named(*paths: str) -> Members:
    return lambda module: list(paths)


def classes_named(where: str, suffix: str) -> Members:
    """Every class declared in ``where`` whose name ends in ``suffix``.

    By name rather than by list: a step type or selector form added to the
    models turns up in the docs without anyone remembering to add it here.
    An imported name is an alias, never a declaration, so it is skipped.
    """

    def found(module: griffe.Module) -> list[str]:
        classes = module[where].classes
        return [
            f"{where}.{name}"
            for name, member in classes.items()
            if name.endswith(suffix) and not member.is_alias
        ]

    return found


def step_models(module: griffe.Module) -> list[str]:
    extra = ["models.MatchFields", "models.SaveAs", "models.TargetSpec"]
    return classes_named("models", "Step")(module) + extra


DOCUMENTS: dict[str, Document] = {
    "reference/steps": Document(
        "Steps",
        "Every `action:` a flow can write, as the model that validates it. "
        "`BaseStep` holds the options every step takes; `SelectorStep` and "
        "`MatchFields` hold the ones every targeting step takes.",
        step_models,
    ),
    "reference/selectors": Document(
        "Selectors",
        "How a step names the element it acts on. A bare string is a CSS "
        "selector; these are the explicit spellings.",
        classes_named("selectors", "Selector"),
    ),
    "reference/waits": Document(
        "Wait states",
        "What `wait_for` waits for, and which states a `text:` wait accepts.",
        named(
            "models.WaitState",
            "models.WAIT_STATES",
            "models.TEXT_STATES",
            "models.check_text_state",
            "models.WaitForStep",
        ),
    ),
    "reference/behavior": Document(
        "Behavior",
        "The humanization knobs a run can be given, and the presets that set them.",
        named("behavior.Behavior", "behavior.Jitter", "behavior.profile"),
    ),
    "reference/results": Document(
        "Flow results",
        "What a run hands back, successful or not.",
        named(
            "models.FlowSuccess",
            "models.FlowError",
            "models.RetryHint",
            "models.SkippedStep",
            "models.MatchWarning",
            "results.AcceptedMatch",
            "results.BytesResult",
        ),
    ),
    "reference/extract": Document(
        "Extract specs",
        "What a `read` step's `extract:` writes, one entry per column.",
        named("parse.ExtractField", "parse.ParseBase", "parse.build_model"),
        QUIET,
    ),
    "reference/session": Document(
        "BrowserSession",
        "The Python surface every flow step is built on; an embedding caller "
        "drives the same methods directly.",
        named("session.BrowserSession"),
        QUIET,
    ),
}


def load_package(source: Path) -> griffe.Module:
    """The package as griffe reads it — statically, without importing it."""
    loaded = griffe.load(
        PACKAGE,
        search_paths=[str(source)],
        extensions=griffe.load_extensions("griffe_pydantic"),
        resolve_aliases=True,
    )
    assert isinstance(loaded, griffe.Module)
    return loaded


def render(module: griffe.Module, document: Document) -> str:
    config = {**CONFIG, **document.config}
    bodies = [
        griffe2md.render_object_docs(module[path], config)
        for path in document.members(module)
    ]
    return "\n".join([HEADER, f"# {document.title}\n", document.intro, "", *bodies])


def reference_documents(source: Path) -> dict[str, str]:
    """Every generated document, keyed by its doc name."""
    module = load_package(source)
    return {name: render(module, document) for name, document in DOCUMENTS.items()}


def reference_dir(source: Path) -> Path:
    return source / PACKAGE / "docs" / "reference"


def write_reference(source: Path) -> list[str]:
    """Write every document under ``source``; answer the names that changed."""
    target = reference_dir(source)
    target.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, text in reference_documents(source).items():
        path = target / f"{Path(name).name}.md"
        if not path.exists() or path.read_text() != text:
            path.write_text(text)
            changed.append(name)
    for orphan in orphans(source):
        orphan.unlink()
        changed.append(f"removed {orphan.name}")
    return changed


def orphans(source: Path) -> list[Path]:
    """Files left behind by a document that was renamed or dropped."""
    wanted = {f"{Path(name).name}.md" for name in DOCUMENTS}
    target = reference_dir(source)
    if not target.exists():
        return []
    return sorted(path for path in target.glob("*.md") if path.name not in wanted)


def stale_reference(source: Path) -> list[str]:
    """What a rebuild would change: drift, missing files and orphans alike."""
    target = reference_dir(source)
    stale = [
        name
        for name, text in reference_documents(source).items()
        if not (path := target / f"{Path(name).name}.md").exists()
        or path.read_text() != text
    ]
    return stale + [f"orphan {path.name}" for path in orphans(source)]
