"""The reference half of the docs, written by reading the models.

``reference_documents()`` returns ``{name: markdown}`` for every generated
file under ``docs/reference/``; ``llm-browser docs --write`` puts them there
and ``tests/test_docs.py`` fails when what ships no longer matches. Nothing
here is hand-edited, so a field's meaning is maintained once, on the field.
"""

from pathlib import Path

from llm_browser import constants
from llm_browser.doc_render import (
    docstring,
    field_table,
    model_section,
    render_signature,
    render_value,
    table,
)
from llm_browser.behavior import Behavior
from llm_browser.introspect import own_fields, session_methods, step_arms
from llm_browser.models import (
    TEXT_STATES,
    WAIT_STATES,
    BaseStep,
    MatchFields,
    SelectorStep,
    FlowError,
    FlowSuccess,
    MatchWarning,
    RetryHint,
    SkippedStep,
)
from llm_browser.parse import ExtractField
from llm_browser.selectors import (
    CssSelector,
    FallbackSelector,
    IdSelector,
    RefSelector,
    ScopedSelector,
    XpathSelector,
)
from llm_browser.session import BrowserSession

HEADER = (
    "<!-- Generated by `llm-browser docs --write`; edit the models, "
    "not this file. -->\n"
)


def docs_dir() -> Path:
    return Path(__file__).parent / "docs"


# --- The documents ---


# Written once under "Targeting" rather than in all fifteen step sections.
SHARED_TARGET_FIELDS = set(MatchFields.model_fields) | {"selector"}


def local_fields(step_class: type[BaseStep]) -> list[str]:
    """A step's own rows: the targeting fields are documented once, unless the
    step redeclares one to mean something different."""
    declared = getattr(step_class, "__annotations__", {})
    return [
        name
        for name in own_fields(step_class)
        if name not in SHARED_TARGET_FIELDS or name in declared
    ]


def targeting_section() -> str:
    names = ["selector", *MatchFields.model_fields]
    return (
        "## Targeting\n\n"
        "Every step that acts on an element takes these; a step that "
        "redeclares one says so in its own table.\n\n"
        + field_table(SelectorStep, names)
    )


def steps_document() -> str:
    sections = [
        model_section(f"`{action}`", step_class, local_fields(step_class))
        for action, step_class in step_arms()
    ]
    return (
        "# Steps\n\n"
        "One section per `action:` a flow can write. Every step also takes the "
        "targeting fields and the shared options at the end.\n\n"
        + "\n".join(sections)
        + "\n"
        + targeting_section()
        + "\n"
        + model_section("Shared options", BaseStep)
    )


def selectors_document() -> str:
    forms = (
        CssSelector,
        XpathSelector,
        IdSelector,
        RefSelector,
        FallbackSelector,
        ScopedSelector,
    )
    intro = (
        "How a step names the element it acts on. A bare string is a CSS "
        "selector; the forms below are the explicit spellings.\n"
    )
    return (
        "# Selectors\n\n"
        + intro
        + "\n"
        + "\n".join(model_section(f"`{form.__name__}`", form) for form in forms)
    )


def waits_document() -> str:
    rows = [
        [f"`{state}`", meaning, "yes" if state in TEXT_STATES else "no"]
        for state, meaning in WAIT_STATES.items()
    ]
    return (
        "# Wait states\n\n"
        "What `wait_for` (and any step's own wait) can wait for. The last "
        "column says whether a `text:` wait accepts the state — text is read "
        "off `innerText`, so only presence and absence mean anything.\n\n"
        + table(["state", "element is", "valid for `text:`"], rows)
    )


def behavior_document() -> str:
    presets = [
        ("human", Behavior.human()),
        ("pace", Behavior.pace()),
        ("off", Behavior.off()),
    ]
    rows = [
        [f"`{name}`", field.description or ""]
        + [f"`{render_value(getattr(preset, name))}`" for _, preset in presets]
        for name, field in Behavior.model_fields.items()
    ]
    return (
        "# Behavior\n\n"
        + docstring(Behavior)
        + "\n\nA run picks a preset by name; a flow that needs one knob "
        "different sets it and the run reports `custom`.\n\n"
        + table(
            ["knob", "meaning", *[f"`{name}`" for name, _ in presets]],
            rows,
        )
    )


def results_document() -> str:
    models = (FlowSuccess, FlowError, RetryHint, SkippedStep, MatchWarning)
    return "# Flow results\n\n" + "\n".join(
        model_section(f"`{model.__name__}`", model) for model in models
    )


def extract_document() -> str:
    return "\n".join(
        [
            "# Extract specs\n",
            "What a `read` step's `extract:` writes, one entry per column.\n",
            "## The compact form\n",
            docstring(ExtractField.parse) + "\n",
            "## The mapping form\n",
            docstring(ExtractField) + "\n",
            "## Readable properties\n",
            "Every name below is read as a JavaScript property; anything else "
            f"is an HTML attribute. The default is `{constants.DEFAULT_EXTRACT_ATTRIBUTE}`, "
            f"under the field name `{constants.DEFAULT_EXTRACT_FIELD}` when the spec "
            "names no fields.\n",
            "\n".join(f"- `{name}`" for name in constants.EXTRACT_PROPERTIES) + "\n",
            "A `read` step's `exclude:` only changes the properties a "
            "descendant is part of: "
            + ", ".join(f"`{name}`" for name in constants.EXCLUDABLE_PROPERTIES)
            + ".\n",
        ]
    )


def signature_of(name: str) -> str:
    return render_signature(name, getattr(BrowserSession, name))


def session_document() -> str:
    sections = [
        f"## `{signature_of(name)}`\n\n{docstring(getattr(BrowserSession, name))}\n"
        for name in session_methods()
    ]
    return (
        "# BrowserSession\n\n"
        "The Python surface every flow step is built on; an embedding caller "
        "drives the same methods directly.\n\n" + "\n".join(sections)
    )


DOCUMENTS = {
    "reference/steps": steps_document,
    "reference/selectors": selectors_document,
    "reference/waits": waits_document,
    "reference/behavior": behavior_document,
    "reference/results": results_document,
    "reference/extract": extract_document,
    "reference/session": session_document,
}


def reference_documents() -> dict[str, str]:
    """Every generated document, keyed by its doc name."""
    return {name: HEADER + "\n" + build() for name, build in DOCUMENTS.items()}


def write_reference() -> list[str]:
    """Write every document into the package; answer the paths that changed."""
    changed = []
    for name, text in reference_documents().items():
        path = docs_dir() / f"{name}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != text:
            path.write_text(text)
            changed.append(name)
    return changed


def stale_reference() -> list[str]:
    """Documents whose shipped text no longer matches the models."""
    return [
        name
        for name, text in reference_documents().items()
        if not (docs_dir() / f"{name}.md").exists()
        or (docs_dir() / f"{name}.md").read_text() != text
    ]
